---
title: My Portfolio
author: Christopher Buss
email: christopher.buss@pm.me
description: Welcome to my portfolio.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
